export const DISCONNECT_SOCKET = 'DISCONNECT_SOCKET';
export const CONNECT_SOCKET = 'CONNECT_SOCKET';

export const JOIN_CHAT_ROOM = 'JOIN_CHAT_ROOM';
export const WAIT_FOR_MATCHING = 'WAITING_FOR_MATCHING';
export const MATCHED_PARTNER = 'MATCHED_PARTNER';
export const LEAVE_CHAT_ROOM = 'LEAVE_CHAT_ROOM';

export const CHANGE_INPUT_USERNAME = 'CHANGE_INPUT_USERNAME';
export const CHANGE_INPUT_MESSAGE = 'CHANGE_INPUT_MESSAGE';
export const INIT_INPUT_MESSAGE = 'INIT_INPUT_MESSAGE';

export const START_PARTNER_WRITING = 'START_PARTNER_WRITING';
export const COMPLETE_PARTNER_WRITING = 'COMPLETE_PARTNER_WRITING';
export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';
export const INIT_MESSAGES = 'INIT_MESSAGES';
export const RECIEVE_START_MESSAGE = 'RECIEVE_START_MESSAGE';
export const RECIEVE_END_MESSAGE = 'RECIEVE_END_MESSAGE';
